config/routes.rb
Rails.application.routes.draw do
  get 'pages/privacy'
  get 'pages/terms'
  get 'pages/contact'
  get 'pages/presentation'

  # Routes pour la gestion des utilisateurs avec Devise
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  # Redirection après connexion (utilisateurs authentifiés)
  authenticated :user do
    root 'stories#index', as: :authenticated_root
  end

  # Redirection pour les utilisateurs non connectés (page d'accueil)
  unauthenticated do
    root 'home#index', as: :unauthenticated_root
  end

  # Routes pour les stories et les chapitres
  resources :stories do
    # Routes imbriquées pour les chapitres
    resources :chapters, except: [:index] do
      # Routes imbriquées pour les commentaires (sur les chapitres)
      resources :comments, only: [:create, :destroy]
    end

    # Routes imbriquées pour les commentaires (sur les stories)
    resources :comments, only: [:create, :destroy]

    # Route pour liker une histoire
    post 'like', to: 'likes#create'
    delete 'unlike', to: 'likes#destroy'
  end

  resources :stories, param: :id do
    member do
      post 'analyze', to: 'stories#analyze'
    end
  end

  resources :chapters do
    resources :comments, only: [:create, :destroy]
  end

  # Routes pour les catégories
  resources :categories, only: [:index, :show]

  # Routes pour voir le profil de l'utilisateur, ses histoires, etc.
  resources :users, only: [:show] do
    collection do
      post :update_color # Route personnalisée pour mettre à jour la couleur
    end
  end

  get 'search', to: 'stories#search', as: 'search_stories'

  # Pages statiques
  get 'privacy', to: 'pages#privacy'
  get 'terms', to: 'pages#terms'
  get 'contact', to: 'pages#contact'
  get 'presentation', to: 'pages#presentation'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :stories
  has_many :comments
  has_many :likes

  has_many :reads, dependent: :destroy
  has_many :read_stories, through: :reads, source: :story
  has_many :read_chapters, through: :reads, source: :chapte

  validates :first_name, :last_name, :city, :gender, presence: true, allow_blank: true
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  # Permettre la mise à jour de l'utilisateur sans fournir le mot de passe
  def update_resource(resource, params)
    if params[:password].blank? && params[:password_confirmation].blank?
      resource.update_without_password(params.except(:current_password))
    else
      super
    end
  end

  def configure_permitted_parameters
    # Pour l'inscription (sign_up)
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username, :city, :gender, :bio, :email, :password, :password_confirmation, :dark_mode])

    # Pour la mise à jour du compte (account_update)
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :username, :city, :gender, :bio, :email, :password, :password_confirmation, :dark_mode])
  end
end




  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  #

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @stories = @user.stories

    if user_signed_in?

            @read_stories = Story.joins(:reads)
                           .where(reads: { user_id: current_user.id })
                           .where.not(user_id: current_user.id)
                           .group('stories.id')
                           .order('MAX(reads.created_at) DESC')
                           .limit(8)
        @last_read_chapters = @read_stories.map do |story|
        story.last_read_chapter_for_user(current_user)
      end
    else
      @read_stories = []
    end
  end

  def update_color
    if current_user.update(user_params)
      Rails.logger.info "Couleur mise à jour pour #{current_user.username} : #{current_user.primary_color}"
      render json: { message: 'Couleur mise à jour avec succès' }, status: :ok
    else
      render json: { error: 'Erreur lors de la mise à jour de la couleur' }, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:primary_color, :opposite_color)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<div class="user-profile-container">
  <!-- Informations de l'utilisateur -->
  <div class="user-details card">
    <h1>Profil de <%= @user.username || @user.email %></h1>
    <p><strong>Nom :</strong> <%= @user.first_name %> <%= @user.last_name %></p>
    <p><strong>Ville :</strong> <%= @user.city || 'Non renseigné' %></p>
    <p><strong>Username:</strong> <%= @user.username %></p>
    <p><strong>Email :</strong> <%= @user.email %></p>
    <p><strong>Bio :</strong> <%= @user.bio.present? ? @user.bio : 'Aucune biographie disponible.' %></p>

    <%= link_to 'Modifier mon profil', edit_user_registration_path, class: 'btn btn-primary' %>
  </div>

  <!-- Dernières histoires lues -->
  <div class="user-details card section">
  <% if user_signed_in? && @read_stories.any? %>
    <div class="last-read section">
      <h1>Dernières histoires lues</h1>
      <div class="stories-list">
        <% @read_stories.each do |story| %>
          <div class="card-index list-item">
            <div>
              <h3 class="card-index__title"><%= link_to story.title, story_path(story) %></h3>
              <span class="card-index__tagline">par <%= story.user.username %></span>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
  </div>

  <!-- Section des histoires de l'utilisateur -->
  <div class="my-stories card section">
    <h2>Les histoires au top par <%= @user.username %></h2>

    <% if @stories.any? %>
      <div class="stories-grid">
        <% @stories.each do |story| %>
          <div class="story-card">
          <h2><%= link_to story.title, story_path(story), class: "story-title" %></h2>

            <!-- Image de couverture ou image par défaut -->
            <% if story.cover_image_url.present? %>
              <%= image_tag story.cover_image_url, alt: "Couverture de #{story.title}", class: "story-cover" %>
            <% else %>
              <%= image_tag "default.jpg", alt: "Couverture de #{story.title}", class: "story-cover" %>
            <% end %>

            <!-- Informations sur l'histoire -->
            <div class="story-info">
              <p class="story-description"><%= story.description %></p>

              <div class="story-actions">
                <%= link_to story_path(story), class: 'btn btn-read' do %>
                  Lire
                <% end %>
                <%= link_to edit_story_path(story), class: 'btn btn-edit' do %>
                  Modifier
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% else %>
      <p>Aucune histoire pour le moment.</p>
    <% end %>

    <!-- Bouton pour créer une nouvelle histoire -->
    <%= link_to 'Nouvelle histoire', new_story_path, class: 'btn btn-create' %>
  </div>

  <!-- Lien de retour -->
  <div class="back-link">
    <%= link_to 'Retour aux histoires', stories_path, class: 'btn btn-secondary' %>
  </div>
</div>