config/routes.rb
Rails.application.routes.draw do
  get 'pages/privacy'
  get 'pages/terms'
  get 'pages/contact'
  get 'pages/presentation'

  # Routes pour la gestion des utilisateurs avec Devise
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  # Redirection après connexion (utilisateurs authentifiés)
  authenticated :user do
    root 'stories#index', as: :authenticated_root
  end

  # Redirection pour les utilisateurs non connectés (page d'accueil)
  unauthenticated do
    root 'home#index', as: :unauthenticated_root
  end

  # Routes pour les stories et les chapitres
  resources :stories do
    # Routes imbriquées pour les chapitres
    resources :chapters, except: [:index] do
      # Routes imbriquées pour les commentaires (sur les chapitres)
      resources :comments, only: [:create, :destroy]
    end

    # Routes imbriquées pour les commentaires (sur les stories)
    resources :comments, only: [:create, :destroy]

    # Route pour liker une histoire
    post 'like', to: 'likes#create'
    delete 'unlike', to: 'likes#destroy'
  end

  resources :stories, param: :id do
    member do
      post 'analyze', to: 'stories#analyze'
    end
  end

  resources :chapters do
    resources :comments, only: [:create, :destroy]
  end

  # Routes pour les catégories
  resources :categories, only: [:index, :show]

  # Routes pour voir le profil de l'utilisateur, ses histoires, etc.
  resources :users, only: [:show] do
    collection do
      post :update_color # Route personnalisée pour mettre à jour la couleur
    end
  end

  get 'search', to: 'stories#search', as: 'search_stories'

  # Pages statiques
  get 'privacy', to: 'pages#privacy'
  get 'terms', to: 'pages#terms'
  get 'contact', to: 'pages#contact'
  get 'presentation', to: 'pages#presentation'
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  has_rich_text :content

  belongs_to :story
  after_save :update_story_timestamp

  before_create :set_position
  after_destroy :reorder_positions

  has_many :reads, dependent: :destroy
  has_many :users_who_read, through: :reads, source: :user
  has_many :comments, as: :commentable, dependent: :destroy

  validates :position, uniqueness: { scope: :story_id }

  def previous_chapter
    story.chapters.where("position < ?", self.position).order(position: :desc).first
  end

  def next_chapter
    story.chapters.where("position > ?", self.position).order(position: :asc).first
  end

  def reading_time
    word_count = self.content.to_plain_text.split.size
    minutes = (word_count / 200.0).ceil

    if minutes < 60
      "#{minutes} minute#{'s' if minutes > 1}"
    else
      hours = minutes / 60
      remaining_minutes = minutes % 60
      "#{hours} hour#{'s' if hours > 1} #{remaining_minutes} minute#{'s' if remaining_minutes > 1}"
    end
  end

  private

  def update_story_timestamp
    story.touch
  end

  def set_position
    # max_position = story.chapters.maximum(:position)
  self.position ||= story.chapters.maximum(:position).to_i + 1
  end

  def reorder_positions
    story.chapters.order(:position).each_with_index do |chapter, index|
      chapter.update(position: index + 1)
    end
  end
end

app/controllers/chapters_controller.rb
require 'net/http'
require 'uri'
require 'json'
require 'concurrent'

class ChaptersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_story
  before_action :set_chapter_by_position, only: [:show, :destroy]
  before_action :set_chapter_by_id, only: [:edit, :update]

require 'docx'
require 'pdf-reader'
require 'odf'

  MAX_TEXT_LENGTH = 20000

  def show
    Read.mark_as_read(current_user, @story, @chapter) if user_signed_in?
  end

  def new
    @chapter = @story.chapters.build
  end

  def create
    @chapter = @story.chapters.build(chapter_params)

    # Réinitialiser les informations d'analyse avant une nouvelle analyse
    reset_analysis_info

    # Vérifier s'il y a des pièces jointes via ActionText (dans ActiveStorage)
    if @chapter.content.body.attachments.any?
      attachment = @chapter.content.body.attachments.first
      if valid_attachment?(attachment)
        extracted_text = extract_text_from_attachment(attachment)
        if extracted_text
          @chapter.content = ActionText::Content.new(extracted_text)  # Remplacer le contenu par le texte extrait
        else
          flash.now[:alert] = "Impossible d'extraire le texte de la pièce jointe."
          return render :new
        end
      else
        flash.now[:alert] = "Seuls les fichiers PDF, DOCX, et ODT sont acceptés."
        return render :new
      end
    end

    # Effectuer l'analyse
    analysis_result = analyze_text_with_gpt(@chapter.content)

    # Mettre à jour le feedback et le score dans la base de données
    update_chapter_analysis_info(analysis_result)

    if analysis_result[:passed]
      if @chapter.save
        flash[:notice] = "Chapitre créé avec succès. Qualité du texte : #{@chapter.analysis_score}%."
        respond_to do |format|
          format.html { redirect_to story_chapter_path(@story, @chapter.position, show_modal: true) }
          format.turbo_stream { render_flash }
        end
      else
        flash.now[:alert] = 'Erreur lors de la création du chapitre.'
        respond_to do |format|
          format.html { render :new, locals: { show_modal: true } }
          format.turbo_stream { render_flash }
        end
      end
    else
      flash.now[:alert] = "Le texte a échoué à l'analyse avec un score de #{@chapter.analysis_score}%. #{@chapter.analysis_feedback}"
      respond_to do |format|
        format.html { render :new, locals: { show_modal: true } }
        format.turbo_stream { render_flash }
      end
    end
  end

  def update
    @chapter = @story.chapters.build(chapter_params)

    # Réinitialiser les informations d'analyse avant une nouvelle analyse
    reset_analysis_info

    # Effectuer l'analyse
    analysis_result = analyze_text_with_gpt(@chapter.content)

    # Mettre à jour le feedback et le score dans la base de données
    update_chapter_analysis_info(analysis_result)

    if analysis_result[:passed]
      if @chapter.save
        flash[:notice] = "Chapitre mis à jour avec succès. Qualité du texte : #{@chapter.analysis_score}%."
        respond_to do |format|
          format.html { redirect_to story_chapter_path(@story, @chapter.position, show_modal: true) }
          format.turbo_stream { render_flash }
        end
      else
        flash.now[:alert] = 'Erreur lors de la mise à jour du chapitre.'
        respond_to do |format|
          format.html { render :edit, locals: { show_modal: true } }
          format.turbo_stream { render_flash }
        end
      end
    else
      flash.now[:alert] = "Le texte a échoué à l'analyse avec un score de #{@chapter.analysis_score}%. #{@chapter.analysis_feedback}"
      respond_to do |format|
        format.html { render :edit, locals: { show_modal: true } }
        format.turbo_stream { render_flash }
      end
    end
  end

  def destroy
    @chapter.destroy
    flash[:notice] = 'Chapitre supprimé avec succès.'
    respond_to do |format|
      format.html { redirect_to story_path(@story) }
      format.turbo_stream { render_flash }
    end
  end

  private

  def set_story
    @story = Story.find_by!(slug: params[:story_id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "Histoire introuvable."
    redirect_to stories_path
  end

  def set_chapter_by_position
    @chapter = @story.chapters.find_by!(position: params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "Chapitre introuvable pour la position donnée."
    redirect_to story_path(@story)
  end

  def set_chapter_by_id
    @chapter = @story.chapters.find(params[:id])
  end

  def chapter_params
    params.require(:chapter).permit(:title, :content)
  end

  def reset_analysis_info
    @chapter.analysis_score = nil
    @chapter.analysis_feedback = nil
  end

  def update_chapter_analysis_info(analysis_result)
    @chapter.analysis_feedback = feedback_message(analysis_result)
    @chapter.analysis_score = analysis_result[:final_score]
    session[:feedback] = @chapter.analysis_feedback
    session[:analysis_score] = @chapter.analysis_score
  end

  def valid_attachment?(attachment)
    Rails.logger.info "Attachment content_type: #{attachment.content_type}"
    Rails.logger.info "Valid content types: #{%w(application/pdf application/vnd.openxmlformats-officedocument.wordprocessingml.document application/vnd.oasis.opendocument.text)}"

    valid = attachment.content_type.in?(%w(application/pdf application/vnd.openxmlformats-officedocument.wordprocessingml.document application/vnd.oasis.opendocument.text))

    if valid
      Rails.logger.info "Fichier valide : #{attachment.content_type}"
    else
      Rails.logger.error "Fichier non valide : #{attachment.content_type}"
    end

    valid
  end

# Méthode pour extraire le texte de la pièce jointe
  def extract_text_from_attachment(attachment)
    Rails.logger.info "Début de l'extraction de texte pour le fichier : #{attachment.filename} (#{attachment.content_type})"

    if attachment.content_type == 'application/pdf'
      Rails.logger.info "Traitement d'un fichier PDF"
      extract_text_from_pdf(attachment)
    elsif attachment.content_type == 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
      Rails.logger.info "Traitement d'un fichier DOCX"
      extract_text_from_docx(attachment)
    elsif attachment.content_type == 'application/vnd.oasis.opendocument.text'
      Rails.logger.info "Traitement d'un fichier ODT"
      extract_text_from_odt(attachment)
    else
      Rails.logger.error "Type de fichier non supporté : #{attachment.content_type}"
      nil
    end
  end


  def extract_text_from_pdf(attachment)
    begin
      # Télécharge le fichier PDF
      pdf_io = StringIO.new(attachment.download.force_encoding('BINARY'))  # Assure que le contenu est binaire
      reader = PDF::Reader.new(pdf_io)

      text = ''
      reader.pages.each do |page|
        text += page.text.encode('UTF-8', invalid: :replace, undef: :replace, replace: '') + "\n"
      end

      text
    rescue StandardError => e
      Rails.logger.error "Erreur lors de l'extraction du PDF: #{e.message}"
      nil
    end
  end


  def extract_text_from_docx(attachment)
    doc = Docx::Document.open(StringIO.new(attachment.download))
    text = doc.paragraphs.map(&:text).join("\n")
    text
  rescue StandardError => e
    Rails.logger.error "Erreur lors de l'extraction du DOCX: #{e.message}"
    nil
  end

  def extract_text_from_odt(attachment)
    odt = ODF::Text.new(StringIO.new(attachment.download))
    odt.text
  rescue StandardError => e
    Rails.logger.error "Erreur lors de l'extraction de l'ODT: #{e.message}"
    nil
  end

  def analyze_text_with_gpt(content)
    plain_text_content = content.to_s

    # 1. Analyse de la lisibilité, vulgarité, répétitions, etc.
    readability_result = analyze_readability_with_gpt(plain_text_content)

    # 2. Évaluation de la qualité en tant que chapitre de livre
    chapter_quality_result = evaluate_chapter_quality_with_gpt(plain_text_content)

    # 3. Feedback détaillé et concis de GPT
    # detailed_feedback_result = call_gpt_for_detailed_feedback(plain_text_content, chapter_quality_result[:score])

    # 4. Calcul de la nouvelle moyenne avec le score de lisibilité, qualité, et feedback
    final_score = (readability_result[:score] + chapter_quality_result[:score]) / 2.0

    {
      final_score: final_score.round(2),
      readability_feedback: readability_result[:feedback],
      chapter_quality_feedback: chapter_quality_result[:feedback],
      # detailed_feedback: detailed_feedback_result[:feedback],
      passed: final_score >= 70
    }
  end

def analyze_readability_with_gpt(content)
  client = OpenAI::Client.new(access_token: ENV['OPENAI_API_KEY'])
  prompt = "Analyse ce texte en tant que critique littéraire en examinant les éléments suivants :
              - **Respect des conventions littéraires** (note sur 5),
              - **Structre du texte** (note sur 5),
              - **Vocabulaire** (note sur 5),
              - **Originalité** (note sur 5),
              - **Orthographe** (note sur 5),
              - **Grammaire** (note sur 5),
              - **Conjugaison** (note sur 5),
              - **Complexité** (note sur 5),
              - **Absence de vulgarité** (5 si aucune, 0 si trop présente),
              - **Fluidité** (note sur 5).

            N'indique pas le calcul. Multipilie le total par 2 et ne donne (obligatoirement) que la note sur 100. Justifie ta note en deux phrases, en te gardant d'être trop gentil.
            Voici le texte : #{content}"

  begin
    response = client.chat(
      parameters: {
        model: "gpt-3.5-turbo",
        messages: [
          { role: "system", content: "Tu es un expert en linguistique et littérature. Évalue les textes de manière précise et concise en fonction des conventions littéraires classiques." },
          { role: "user", content: prompt }
        ],
        max_tokens: 300  # Limiter le nombre de tokens pour forcer la concision
      }
    )

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/views/chapters/_form_chapter.html.erb
<div class="chapter-edit-container">
  <div class="chapter-form card">
    <%= form_with(model: [@story, @chapter]) do |form| %>
      <div class="form-group">
        <%= form.label :title, "Titre du Chapitre", class: 'form-label' %>
        <%= form.text_field :title, class: 'form-control input-field' %>
      </div>

      <div class="form-group">
        <%= form.label :content, "Contenu du Chapitre", class: 'form-label' %>
        <%= form.rich_text_area :content %>
      </div>

      <div class="form-actions">
        <%= form.submit "Enregistrer le Chapitre", class: 'btn btn-primary' %>
        <%= link_to 'Retour à l\'histoire', story_path(@story), class: 'btn btn-secondary' %>
      </div>
      <% end %>
  </div>
</div>

<div id="loading-modal" class="spinner_modal" style="display: none;">
  <div class="modal-content">
  <div class="spinner"></div>
    <p>Analyse en cours, veuillez patienter...</p>
  </div>
</div>

app/views/chapters/edit.html.erb
<%= render 'form_chapter', story: @story, chapter: @chapter %>

app/views/chapters/new.html.erb
<% if @score.present? %>
  <p>Le score de qualité du texte est : <strong><%= @score %>%</strong></p>
  <% if @score < 70 %>
    <p style="color: red;">Le texte doit avoir un score d'au moins 75% pour être validé.</p>
  <% end %>
<% end %>
<%= render 'form_chapter', story: @story, chapter: @chapter %>

app/views/chapters/show.html.erb
<div class="chapter-show-container">
  <!-- Titre et contenu du chapitre -->
  <div class="chapter-details card">
    <h1 class="chapter-title"><%= @chapter.title %></h1>
    <p>Temps de lecture estimé : <%= @chapter.reading_time %></p>
    <div class="chapter-content">
      <div class="chapter-content">
        <%= @chapter.content %>
      </div>
    </div>

    <!-- Boutons pour éditer et supprimer le chapitre (pour l'auteur) -->
    <% if current_user == @story.user %>
      <div class="chapter-actions">
        <%= link_to '✏️ Editer', edit_story_chapter_path(@story, @chapter), class: 'btn btn-edit' %>
        <%= button_to '🗑️ Supprimer le chapitre', story_chapter_path(@story, @chapter.position), method: :delete, data: { confirm: 'Es-tu sûr ?' }, class: 'btn btn-danger' %>
        <%= link_to '➕ Ajouter un chapitre', new_story_chapter_path(@story), class: 'btn btn-primary add-chapter-btn' %>
      </div>
    <% end %>
  </div>

  <div class="chapter-navigation">
    <!-- Lien vers le chapitre précédent s'il existe -->
    <% if @chapter.previous_chapter.present? %>
      <%= link_to '⬅️ Chapitre précédent', story_chapter_path(@story, @chapter.previous_chapter.position), class: 'btn btn-secondary' %>
    <% end %>

    <!-- Lien vers le chapitre suivant s'il existe -->
    <% if @chapter.next_chapter.present? %>
      <%= link_to 'Chapitre suivant ➡️', story_chapter_path(@story, @chapter.next_chapter.position), class: 'btn btn-primary' %>
    <% end %>
  </div>

  <% if user_signed_in? && current_user == @story.user %>
    <div class="chapter-feedback">
      <h3>Rapport d'analyse du chapitre</h3>
      <div class="feedback-content">
        <%= raw @chapter.analysis_feedback %>
      </div>
    </div>
  <% end %>

    <!-- Section des commentaires -->
<% if @story.user != current_user.username %>
  <!-- Formulaire pour ajouter un commentaire -->
  <div class="comment-form card">
    <h2 class="section-title">Ajouter un commentaire</h2>
    <%= form_with(model: [ @chapter, Comment.new ], local: true, class: 'comment-form') do |form| %>
      <div class="form-group">
        <%= form.label :content, "Votre commentaire", class: 'form-label' %>
        <%= form.text_area :content, class: 'form-control', rows: 3 %>
      </div>
      <div class="form-actions">
        <%= form.submit "Poster le commentaire", class: 'btn btn-primary' %>
      </div>
    <% end %>
</div>

<% end %>

<!-- Afficher les commentaires -->
<h2>Commentaires</h2>
<% @chapter.comments.each do |comment| %>
  <div class="comment">
    <p><strong><%= comment.user.username %> :</strong> <%= comment.content %></p>
    <% if comment.user == current_user %>
      <%= link_to 'Supprimer', chapter_comment_path(@chapter, comment), method: :delete, data: { confirm: 'Êtes-vous sûr de vouloir supprimer ce commentaire ?' }, class: 'btn btn-danger' %>
    <% end %>
  </div>
<% end %>

  <!-- Bouton pour retourner à l'histoire -->
  <div class="back-to-story">
    <%= link_to 'Retour à l\'histoire', story_path(@story), class: 'btn btn-secondary' %>
  </div>
</div>